### ISSUE TITLE
Error related to a Web View

### ISSUE THREAD

**Issue by costerik** [YanYuanFE/react-native-signature-canvas#100]
Hey guys, Does this package need to be installed with `react-native-webview`?

Thanks!

```
error: Error: Unable to resolve module `react-native-webview` from `node_modules/react-native-signature-canvas/index.js`: react-native-webview could not be found within the project.
```

**Comment by aliwaqar981** [comment]
Getting same error!

**Comment by aliwaqar981** [comment]
> Hey guys, Does this package need to be installed with `react-native-webview`?
> 
> Thanks!
> 
> ```
> error: Error: Unable to resolve module `react-native-webview` from `node_modules/react-native-signature-canvas/index.js`: react-native-webview could not be found within the project.
> ```

@costerik Did you find any solution?

**Comment by YanYuanFE** [comment]
expo version? react native version? please provide package.json or code example

**Comment by YanYuanFE** [comment]
react-native-signature-canvas use Webview of react-native-webview

**Comment by YanYuanFE** [comment]
```
yarn add react-native-webview
```

**Comment by aliwaqar981** [comment]
Installed Packages:
"react-native-signature-canvas": "^3.4.0",
"react-native-webview": "^11.2.3",

Importing Signature from:
import Signature from 'react-native-signature-canvas';

**Comment by YanYuanFE** [comment]
Check whether your node_modules contains react-native-webview?

**Comment by aliwaqar981** [comment]
My bad. I missed linking react-native-webview. Thanks for help
