### ISSUE TITLE
How to remove active highlight from the buttons?

### ISSUE THREAD

**Issue by TamasFarago** [YanYuanFE/react-native-signature-canvas#101]
Is there any way to remove the highlight from the button when clicked? 

<img width="268" alt="Screenshot 2021-02-05 at 14 06 57" src="https://user-images.githubusercontent.com/67281301/107038460-d893a780-67bc-11eb-9464-71444c916c14.png">

**Comment by YanYuanFE** [comment]
webStyle prop can overlap default css， you can use `outline: none`

**Comment by TamasFarago** [comment]
Where should I apply outline: none? 
.m-signature-pad--footer
  .button {
   outline: none
  }

doesn't work

**Comment by YanYuanFE** [comment]
Please provide your code example

**Comment by TamasFarago** [comment]
const style = `.m-signature-pad {
    font-size: 10px;
    height: 100%;
    width: 100%;
    border: 0px;
    top: 10%
    background-color: rgb(255, 255, 255);
    box-shadow: none;


  }
  .m-signature-pad--body {
    position: relative;
    left: 20px;
    right: 20px;
    top: 20px;
    width: 90%;
    height: 60%;
    bottom: 60px;
    border-radius: 16px;
    background-color: rgba(237,244,248,1);
    border: 0px;
  
  }
  .m-signature-pad--body
  canvas {
    position: absolute;
    left: 0;
    top: 0;
    height: 60%;
    width: 100%;
    height: 100%;
    border-radius: 16px;
    background-color: rgba(237,244,248,1);
    box-shadow: none;
  }
  .m-signature-pad--footer {
    height: 25%;
    outline: none;
    background-color: white;
  }
  .m-signature-pad:before, .m-signature-pad:after {
    display: none;
  }
  .m-signature-pad:after {
    display: none;
  }
  .m-signature-pad--footer
  .description {
    display: none;
  }
 
  .m-signature-pad--footer
  .button {
    position: absolute;
    bottom: 0;
    width: 100px;
    height: 30px;
    line-height: 30px;
    text-align: center;
    color: white;
    border: none;
   outline: none
  
  }
 
  body {
    background-color: white;
    fontFamily: "Fira Sans";
   
  }
  .m-signature-pad--footer
  .button.save {
    width: 100%;
    margin: 0 auto;
    right: 50%;
    height: 40px;
    border-radius: 32px;
    color: white;
    background-color: rgba(23,200,115,1);
    transform: translateX(50%);  
    font-size: 16px;
    font-weight: 600;
   
  }
  .m-signature-pad--footer
  .button.clear {
    left: 50%;
    top: 10%;
    min-height: 10px;
    width: 70%;
    transform: translateX(-50%);
    outline: none;
   
    background-color: transparent;
    color: rgba(34,82,117,1);
    font-size: 15px
    
  }
  .m-signature-pad--footer
  .button.clear:active {
    outline: none;
    box-shadow: none;
    outline: none
  }
 
  
 `;

**Comment by TamasFarago** [comment]
const style = `.m-signature-pad {
    font-size: 10px;
    height: 100%;
    width: 100%;
    border: 0px;
    top: 10%
    background-color: rgb(255, 255, 255);
    box-shadow: none;


  }
  .m-signature-pad--body {
    position: relative;
    left: 20px;
    right: 20px;
    top: 20px;
    width: 90%;
    height: 60%;
    bottom: 60px;
    border-radius: 16px;
    background-color: rgba(237,244,248,1);
    border: 0px;
  
  }
  .m-signature-pad--body
  canvas {
    position: absolute;
    left: 0;
    top: 0;
    height: 60%;
    width: 100%;
    height: 100%;
    border-radius: 16px;
    background-color: rgba(237,244,248,1);
    box-shadow: none;
  }
  .m-signature-pad--footer {
    height: 25%;
    outline: none;
    background-color: white;
  }
  .m-signature-pad:before, .m-signature-pad:after {
    display: none;
  }
  .m-signature-pad:after {
    display: none;
  }
  .m-signature-pad--footer
  .description {
    display: none;
  }
 
  .m-signature-pad--footer
  .button {
    position: absolute;
    bottom: 0;
    width: 100px;
    height: 30px;
    line-height: 30px;
    text-align: center;
    color: white;
    border: none;
   outline: none
  
  }
 
  body {
    background-color: white;
    fontFamily: "Fira Sans";
   
  }
  .m-signature-pad--footer
  .button.save {
    width: 100%;
    margin: 0 auto;
    right: 50%;
    height: 40px;
    border-radius: 32px;
    color: white;
    background-color: rgba(23,200,115,1);
    transform: translateX(50%);  
    font-size: 16px;
    font-weight: 600;
   
  }
  .m-signature-pad--footer
  .button.clear {
    left: 50%;
    top: 10%;
    min-height: 10px;
    width: 70%;
    transform: translateX(-50%);
    outline: none;
    background-color: transparent;
    color: rgba(34,82,117,1);
    font-size: 15px
    
  }
  .m-signature-pad--footer
  .button.clear:active {
    outline: none;
    box-shadow: none;
    outline: none
  }
 
  
 `;

**Comment by YanYuanFE** [comment]
add style ```-webkit-tap-highlight-color: transparent;``` for button, work fine after I do.

**Comment by TamasFarago** [comment]
> add style `-webkit-tap-highlight-color: transparent;` for button, work fine after I do.

Worked. Thank you!
