### ISSUE TITLE
trimWhitespace changes imageType

### ISSUE THREAD

**Issue by VLegatus** [YanYuanFE/react-native-signature-canvas#103]
Thank you for the imageType fix!

Unfortunately, the trimWhitespace prop still changes the imageType.

Without trimWhitespace = {true}
data: image/svg+xml; base64,
![without trimWhitespace](https://user-images.githubusercontent.com/19193927/108519622-cffca000-7297-11eb-8642-6cabe58695a6.PNG)

With trimWhitespace = {true}
data: image/png; base64,
![image](https://user-images.githubusercontent.com/19193927/108520619-e5be9500-7298-11eb-95fe-24dc1480dbec.png)

I'll probably find a workaround for now, but I'd like to use this prop someday.

Edit: since the screenshots were tiny, I added the key data above the pics

**Comment by YanYuanFE** [comment]
sorry, trimWhitespace prop no support SVG

**Comment by VLegatus** [comment]
Alright, thanks for the heads up. It would be nice to put that in the ReadMe, but thank you for addressing my issue.
