### ISSUE TITLE
Expo example not working

### ISSUE THREAD

**Issue by Sander165** [YanYuanFE/react-native-signature-canvas#106]
When I try to launch the expo example I get the following error:

_Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef`.
    in WebView (at react-native-signature-canvas/index.js:104)
    in div (created by View)
    in View (at react-native-signature-canvas/index.js:103)
    in ForwardRef (at Sign.js:37)
    in div (created by View)
    in View (at Sign.js:36)
    in Sign (at App.js:43)
    in div (created by View)
    in View (at App.js:33)
    in App (created by ExpoRootComponent)
    in ExpoRootComponent (created by RootComponent)
    in RootComponent
    in div (created by View)
    in View (created by AppContainer)
    in div (created by View)
    in View (created by AppContainer)
    in AppContainer_

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expo-app， this example?
emulator or device? android or ios?
