### ISSUE TITLE
App Crash on Back button pressed

### ISSUE THREAD

**Issue by gioramies** [YanYuanFE/react-native-signature-canvas#109]
I'm using the SignatureScreen component at the bottom of a long ScrollView.

This is the issue:

1. Open the Screen where I'm using the SignatureScreen component.
2. Press device or app back button.
3. App crashes.

I have found that if I scroll the screen until the SignatureScreen component appears in the screen, and press back button, it doesn't crash and works without problems. 
I also found that if press back button when the SignatureScreen is not visible in the screen, the app crashes.

I appreciate your help. Thank you.

**Comment by gioramies** [comment]
I found a solution using: androidHardwareAccelerationDisabled={true}

Check https://github.com/react-native-webview/react-native-webview/issues/811#issuecomment-639833153 (Android is crashing when "WebView" is wrapped by "View")

**Comment by YanYuanFE** [comment]
you can use prop of **androidHardwareAccelerationDisabled=true**

**Comment by gioramies** [comment]
> > you can use prop of **androidHardwareAccelerationDisabled=true**
> 
> Slowing down the application isn't an acceptable solution. It's sad that there are only two big libraries (react-native-signature-capture & this one), and neitheir of them is up to the task.

I had to move to the other library because this one is not compatible with Expo 42, and need to use a modal because the other one have problems with scrollview.

**Comment by Manil-SoftNEP** [comment]
This [answer](https://github.com/react-native-webview/react-native-webview/issues/811#issuecomment-748611465) by [sooakim](https://github.com/sooakim) worked for me. 
Basically set the `androidHardwareAccelerationDisabled` prop (of the parent *View* of the *WebView*) to `true`.
```js
<View
   renderToHardwareTextureAndroid={true}>
   <WebView
        // ...props
   />
</View>
```

If that does not work, setting the [`androidLayerType`](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#androidlayertype) prop (of *WebView*) to `software` worked as well.
```js
<WebView
    // ...props
    androidLayerType={'software'}
/>
```
