### ISSUE TITLE
Cannot sign if component in a `ScrollView`

### ISSUE THREAD

**Issue by jqtruong** [YanYuanFE/react-native-signature-canvas#11]
When the `Signature` component is within a `ScrollView`, trying to sign will cause the view to scroll instead.

**Comment by YanYuanFE** [comment]
You can't use Signature in ScrollView yet. You can try adding a signature button to Scroll, and clicking the button will pop up Modal and display Signature.

**Comment by jqtruong** [comment]
indeed, i did just what you said and it works fine. I thought maybe using `PanResponder` would help with locking the scroll, but could not make it work. Will close for now, thanks.

**Comment by ruegreen** [comment]
Has anyone been able to get this to work in scroll view??  Adding a Modal is not desirable...

**Comment by RobbyWH** [comment]
@ruegreen i think you can use **scrollEnabled** props in the ScrollView, when **onBegin** triggered you can set **scrollEnabled** with false, when **onEnd** triggered you can set scrollEnabled with true

**Comment by isocra** [comment]
I can confirm that @RobbyWH's solution works for me. Thanks!!

**Comment by RobbyWH** [comment]
your welcome @isocra

**Comment by davwheat** [comment]
This doesn't seem to work very well any more.

When using @RobbyWH's method, it scrolls once before allowing me to sign like normal.

Anyone else had this issue/managed to fix it?

See this video for more info: https://u.davwheat.dev/ozBM2i.mp4

**Comment by YanYuanFE** [comment]
@davwheat ,Hi, I think this is not a bug. It is a conflict of interaction design. The touch of ScrollView conflicts with the touch interaction of the signature area. You can try to put the signature component in Modal and add a click button in the ScrollView. When the button is clicked, the display modal, and then sign in the modal.

**Comment by Akshaybagai52** [comment]
Thanks @YanYuanFE for your reply
it worked for me
