### ISSUE TITLE
Unable to Draw Signature After Calling clearSignature()

### ISSUE THREAD

**Issue by mattThousand** [YanYuanFE/react-native-signature-canvas#114]
The signature canvas becomes unresponsive after calling `clearSignature()` - any help would be greatly appreciated! 

Expo version: `40`
Platform: iOS

https://user-images.githubusercontent.com/2637355/111077419-ae6d8d80-84be-11eb-99dc-377f36fd24ba.mp4

```
  const ref = useRef<SignatureViewRef>(null);
  const [signature, setSignature] = useState(null);
...

  const handleSignature = (signature: any) => {
    setSignature(signature);
  };

  const handleClear = () => {
    ref.current?.clearSignature();
  };

  const handleConfirm = () => {
     ...
  };

  const handleEnd = () => {
    ref.current?.readSignature();
  };

...

        <SignatureScreen
          ref={ref}
          onOK={handleSignature}
          onClear={handleClear}
          webStyle={style}
        />

...

            <Button style={styles.button} title={'Clear'} onPress={handleClear} disabled={!validSignature} />
            <Button
              style={styles.button}
              title={'Submit'}
              onPress={handleConfirm}
              disabled={!validSignature}
              isLoading={isUploading}
            />
```

**Comment by ulises-castro** [comment]
How did you solve this?

**Comment by YanYuanFE** [comment]
> > How did you solve this?
> 
> It looks like the `handleClear` function is being used both for the button press handler and for the `onClear` handler of the canvas itself thus causing an infinite loop when the `clearSignature` method is called.

yes, onClear will call after signature canvas be clear, your don't need use onClear when you use clear button
