### ISSUE TITLE
Change style of View around webview 

### ISSUE THREAD

**Issue by Srh07** [YanYuanFE/react-native-signature-canvas#115]
Hi!

I'm trying to change the global background/view. In your files I saw that there's a view wrapped around the actual webview (see code below). I would like to change the border radius of this view. 
For now I solved it with wrapping around another view. Would it be possible in a next update to pass a prop for changing this style? 

Thank you in advance for your feedback!

`<View style={styles.webBg}>
      <WebView
        bounces={false}
        androidHardwareAccelerationDisabled={androidHardwareAccelerationDisabled}
        ref={webViewRef}
        useWebKit={true}
        source={source}
        onMessage={getSignature}
        javaScriptEnabled={true}
        onError={renderError}
        onLoadEnd={() => setLoading(false)}
      />
      {loading && <View style={styles.loadingOverlayContainer}>
        <ActivityIndicator />
      </View>}
    </View>`

**Comment by YanYuanFE** [comment]
ok，I will consider this new feature

**Comment by YanYuanFE** [comment]
v4.0.0, add style prop
