### ISSUE TITLE
Expo 40 - "RNCWKWebView" was not found in the UIManager

### ISSUE THREAD

**Issue by pierreavn** [YanYuanFE/react-native-signature-canvas#124]
Hi, first: thank you for your amazing working!

I'm trying to use the component in Expo v40.0.0 project, but after few attempts, I still have the same error that seems to come from `react-native-webview`:
```
Invariant Violation: requireNativeComponent: "RNCWKWebView" was not found in the UIManager.
```

Do you have any clue about that? Is this component compatible with Expo v40.0.0?
Thank you in advance!

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expo-app,this example is expo v40, "react-native-webview": "^11.2.3", see this version is match.

**Comment by pierreavn** [comment]
Thank you for your answer. The fix was to install `react-native-webview` through expo installer via:
```
expo install react-native-webview
```
This step is needed with expo to link the package natively. Maybe this should be mentioned in the Readme.
Thank you again!
