### ISSUE TITLE
onOk does not work in Android / I cannot get the URI

### ISSUE THREAD

**Issue by miguelcapco** [YanYuanFE/react-native-signature-canvas#147]
Hi.. For some reason the library does not trigger onOK method when the button is pressed. I have tested ref.current.readSignature() method, but it always return undefined or null.. I put a console.log into onOk but it is not called.. I tried with the default buttons and custom buttons.. none works.. I cannot get the uri from the signature pad.

I am using: 
react native cli: 2.0.1
react native 0.64.0
react native signature canvas: 4.0.0
react native webview: 11.4.0

Part of my code is: 

```
// Data
  const [signatureImage, setSignature] = useState(null)

  const ref = useRef();

  // A function that use ref to clear the canvas
  const clear = () => {
    ref.current.clearSignature();
    console.log('Clear..');
    setSignature(null);
  }

  // Implementing methods
  const handleEmpty = () => {
    console.log('The canvas is empty');
  }

  const saveSignature = signature => {
    console.log('saveSignature method');
    setSignature(signature);
  };

  const handleConfirm = () => {
    console.log('Saving signature (handleConfirm)..');
    console.log('------------------');
    console.log(signatureImage);
    console.log('------------------');
  }

  const signStyle = `.m-signature-pad--footer
  .save {
    background-color: #0570AE;
    color: #FFF;
  }
  .clear {
    background-color: #0570AE;
    color: #000;
  }`

......

    <SignatureScreen
            ref={ref}
            onOk={(img) => {
              setSignature(img);
              console.log('signature');
            }}
            onBegin={() => {
              console.log('begin');
            }}
            onEnd={() => {
              console.log('end');
              console.log(ref.current.readSignature());
            }}
            onClear={() => setSignature(null)}
            webStyle={signStyle}
            descriptionText={'Customer Signature'}
        />

...... //Also, I tried custom buttons

     <View style={signatureStyles.btnRow}>
          <TouchableOpacity onPress={clear} style={signatureStyles.btnClear}>
            <Text style={signatureStyles.clearText}>CLEAR</Text>
          </TouchableOpacity>
          
            <TouchableOpacity
              onPress={handleConfirm}
              style={signatureStyles.btnAccept}
            >
              <Text style={signatureStyles.acceptText}>ACCEPT</Text>
            </TouchableOpacity>
        </View>
```

What have I done wrong?? Thanks!

**Comment by YanYuanFE** [comment]
```
const handleConfirm = () => {
    ref.current.readSignature();
  }
```
**ref.current.readSignature();** don't return base64 url, base64 uri can get by **onOk** callback.

**Comment by miguelcapco** [comment]
Thank you! But it is the problem.. I cannot get the uri using onOk because it is not trigger anytime.. I even used the default button.
`  onOk={(img) => {
              setSignature(img);
              console.log('signature');
   }}`
Does it correct? I pressed the default button and nothing happens. Any thoughts??

**Comment by miguelcapco** [comment]
I started the code again using the basic code.. testing every line.. after a basic implementation the library is working perfectly fine. So, I think my initial code has an implementation error that does not allow to Confirm button to be executed (I am still do not know why) when it is pressed. Thank you! My final code is working fine!

**Comment by kaixuannnn** [comment]
Does anyone think the uri is too long?
