### ISSUE TITLE
Update react-native-webview dependency due to UIWebView deprecation by Apple

### ISSUE THREAD

**Issue by cjsauer** [YanYuanFE/react-native-signature-canvas#15]
Hi there 👋 

Apple has announced that they're going to be deprecating the UIWebView APIs, and will stop accepting apps that use it. Because `react-native-signature-canvas` relies on `react-native-webview`, using this lib would result in the deprecation warning from Apple.

Luckily, `react-native-webview` already has a fix out that removes `UIWebView` from their dependencies. I believe all that is required is to update to the latest version, which is `7.0.1` at the time this issue was created.

You can find plenty of context in the linked issue: https://github.com/react-native-community/react-native-webview/issues/819

Thanks for the awesome lib!

**Comment by YanYuanFE** [comment]
Thanks.
I update react-native-webview to 7.0.1, but report an error of 

> Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.

https://github.com/react-native-community/react-native-webview/issues/832

**Comment by norenz92** [comment]
> Thanks.
> I update react-native-webview to 7.0.1, use expo sdk34, but report an error of
> 
> > Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.
> 
> [react-native-community/react-native-webview#832](https://github.com/react-native-community/react-native-webview/issues/832)

I have the same problem

**Comment by YanYuanFE** [comment]
only wait for expo sdk update,you can use react-native-signature-canvas@1.5.0.

**Comment by norenz92** [comment]
Thanks, it worked

**Comment by YanYuanFE** [comment]
expo sdk v35.0 has fixed.
