### ISSUE TITLE
Update version with new merges / Undo issue

### ISSUE THREAD

**Issue by leneti** [YanYuanFE/react-native-signature-canvas#162]
Hello,

Thank you for this useful library! Could you please update the new version with the merges made on June 10th please? The undo/erase features as well the webviewContainerStyle are some very needed additions and I would like to use them without having to fork the repo.

Also, regarding the undo function - after I load an image with the dataURL prop, if I call the undo function it removes the image as well. Is there anything that can be done?

**Comment by YanYuanFE** [comment]
4.1.0 release, welcome to pr
