### ISSUE TITLE
Undo and Erase deletes background image

### ISSUE THREAD

**Issue by leneti** [YanYuanFE/react-native-signature-canvas#166]
After I load an image with the dataURL prop, if I call the undo function it removes the image as well as anything that was drawn. This is also similar with the erase function, where if you start erasing lines, the image can be erased too (would expect it not to). Is there anything that can be done?

**Comment by YanYuanFE** [comment]
wealcome to submit pr

**Comment by leneti** [comment]
Submitted a pull request with fixed and new features.

**Comment by YanYuanFE** [comment]
react-native-signature-canvas@4.2.0 released.
