### ISSUE TITLE
Save signature with background image

### ISSUE THREAD

**Issue by SatyamBansal** [YanYuanFE/react-native-signature-canvas#170]
Good Day!!
How I can save the signature and background image as a single image. I tried saving it that way but only the signature shows up in the gallery with a white background, not with the provided background image.

**Comment by leneti** [comment]
If you're trying to save the two merged images as a single file for sharing later, you might need to look into something like react-native-images-combine (not sure how or if it would even work). However, if you're just trying to present the signature on the same background in the same app, you could just use the `dataURL` prop of the SignatureView and load the saved signature, then just use the same background image

**Comment by SatyamBansal** [comment]
Thanks!! it worked.

**Comment by sb10122001k** [comment]
Hey @SatyamBansal  did react-native-images-combine worked for you?
