### ISSUE TITLE
How to clear Signature

### ISSUE THREAD

**Issue by HakanAkca** [YanYuanFE/react-native-signature-canvas#19]
Hello 

How to delete the image already present in the signature to make a new one because i have 2 signature pad in one component.

I would like to call a function that clear after action.

Thank's

**Comment by YanYuanFE** [comment]
Signature component has provide a button to clear signature.

**Comment by HakanAkca** [comment]
Is there any way to use it otherwise ?

**Comment by YanYuanFE** [comment]
No，only use clear button of this component.

**Comment by aibars** [comment]
Do you mean that it is not possible to use an external button to clear the canvas?

**Comment by YanYuanFE** [comment]
Yes, external button cannot call the function of canvas.
