### ISSUE TITLE
landscape mode not working

### ISSUE THREAD

**Issue by oohajadya** [YanYuanFE/react-native-signature-canvas#206]
i want to change the portrait mode to landscape mode , if im using rotated={true} there are no changes

**Comment by YanYuanFE** [comment]
it not support dynamic change rotated prop

**Comment by oohajadya** [comment]
then how can i change my entire screen to landscape?

**Comment by YanYuanFE** [comment]
you can use a state to let the component rerender.

```  js 
const [key, setKey] = useState(0);

return (
<>
{key === 1 <Signature/> : <Signature rotated/>}
</>
)
```

**Comment by oohajadya** [comment]
![image](https://user-images.githubusercontent.com/72297271/152490388-a19a7c4d-d8dc-43c8-a4ca-5a3806e1f6bf.png)
i want to make the above screen which is in portrait to the landscape  . my code for it is

const SignatureComponennt = ({screenHeight,screenWidth,onLayoutChange}) => {
    const ref =useRef();

   

   

    const handleSave = (signature) => {
        console.log(signature,'signature')
        
    }

    const handleConfirm= () => {
        console.log('read signature')
        ref.current.readSignature();
    }

    const handleClear = () => {
        console.log('clears the signature')
        ref.current.clearSignature();
    }

    const imgWidth = screenWidth;
    const imgHeight = screenHeight;
    const style = `.m-signature-pad--footer {display: none; margin: 0px;}
                   body,html {
                    width: ${imgWidth}px; height: ${imgHeight}px;}
                    .m-signature-pad--body {border: none;}`;
    
    return(
        
        <View style={[styles.container,{width: imgWidth , height: imgHeight}]} onLayout={onLayoutChange}>
            <SignatureScreen ref={ref} onOK={handleSave} webStyle={style} rotated   />
      <View style={styles.row} >
        <TouchableOpacity onPress={handleClear}>
        <MaterialCommunityIcons name="thumb-down-outline" size={wp(9)} color={colors?.BLUELIGHT} />
        </TouchableOpacity >
        <View>
            <Text style={{color:colors.BLACK,fontFamily:fontFamily.RubikSemiBold,fontSize:fontSizes[16]}}>Sign above</Text>
        </View>
        <TouchableOpacity onPress={handleConfirm}>
            <MaterialCommunityIcons name='thumb-up-outline' size={wp(9)} color={colors?.ORANGE} />
        </TouchableOpacity>
      </View>
        </View>
        
    
    )
     
}

const styles= StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
        
    },
    row: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        alignItems: "center",
        padding:'3%',
        borderTopWidth:1
       // borderWidth:1
      },
    

})

export default SignatureComponenn

**Comment by YanYuanFE** [comment]
if you use rotated props, you need open landscape mode , for example, use **react-native-orientation**

**Comment by oohajadya** [comment]
i didnt get it, if i want to display the screen inlandscape mode i should take help of react-native-oreintation npm package is it?

**Comment by oohajadya** [comment]
whenever im changing the oreintation from portrait to landscape the signature is missing and its showing empty canvas
