### ISSUE TITLE
Question: What is the difference between Signature and SignatureScreen

### ISSUE THREAD

**Issue by josh-thompson13** [YanYuanFE/react-native-signature-canvas#274]
Hi! As the title says, I'm really trying to figure out which component I should use, can someone please tell me the difference between the two?

**Comment by vasu2001** [comment]
I think they are the same thing, both are just different names for the default export from the library.
```
import Signature from "react-native-signature-canvas";
import SignatureScreen from 'react-native-signature-canvas';
```

**Comment by YanYuanFE** [comment]
yes，It's same thing.
