### ISSUE TITLE
Webview Dependency conflict with Expo 47

### ISSUE THREAD

**Issue by arnolicious** [YanYuanFE/react-native-signature-canvas#276]
Expo 47 requires/recommends `react-native-webview@11.23.1` and this does seem to be relevant, since my Android Builds fail, when building using `react-native-webview@11.18.1`

Is there something blocking upgrading the depency of this library to using version `11.23.1`?

**Comment by YanYuanFE** [comment]
4.5.0 has fixed

**Comment by arnolicious** [comment]
Thanks for the quick fix!
