### ISSUE TITLE
Can't get the base64 string using a button that's outside of the component

### ISSUE THREAD

**Issue by aibars** [YanYuanFE/react-native-signature-canvas#28]
Hi, 
I'm trying to use the component but with an own set of buttons to clear and save the signature. 
I'm calling the onOK method via a ref but it fails because it doesn't receive the base64 string. I'm wondering if there is a method that could save a state after the user stops drawing and not by pressing the Done button??

Thank you

**Comment by YanYuanFE** [comment]
No, Done button cannot use ref,You can modify this component code as a custom component, because the signature is a webview, done button require call the canvas function.

**Comment by markafox** [comment]
Added this feature in pull request #44
