### ISSUE TITLE
can't make background transparent it still has a white background

### ISSUE THREAD

**Issue by atefwahab** [YanYuanFE/react-native-signature-canvas#304]
I can't set background of pad to be transparent it has a white background
```
<SignatureScreen
      ref={ref}
      onEnd={handleEnd}
      onOK={handleOK}
      onEmpty={handleEmpty}
      onClear={handleClear}
      onGetData={handleData}
      autoClear={false}
      backgroundColor={'transparent'}
      descriptionText={text}
      webStyle={style}

    />
```

**Comment by Ol1va** [comment]
Hi, look at my props, did it that way

Signature component props
```
webStyle={`.m-signature-pad {background:transparent;border:none;box-shadow:none;height:${canvasHeight}px;} .m-signature-pad--body {border:none;} .m-signature-pad--footer {display: none;} .m-signature-pad--body canvas {box-shadow: none !important;}`}
style={styles.singnatureContainer}
webviewContainerStyle={styles.singnatureContainer}
backgroundColor='transparent'
```
Styles
```
singnatureContainer: {
    backgroundColor: 'transparent',
}
```

**Comment by YanYuanFE** [comment]
only use 
```
backgroundColor={'transparent'}
```
can work fine

**Comment by YanYuanFE** [comment]
![image](https://github.com/YanYuanFE/react-native-signature-canvas/assets/17774285/2e03670a-c1b9-41e1-9c4b-ef51ee7dc0d2)

**Comment by mrchess** [comment]
> webStyle={`.m-signature-pad {background:transparent;border:none;box-shadow:none;height:${canvasHeight}px;} .m-signature-pad--body {border:none;} .m-signature-pad--footer {display: none;} .m-signature-pad--body canvas {box-shadow: none !important;}`}
> style={styles.singnatureContainer}
> webviewContainerStyle={styles.singnatureContainer}
> backgroundColor='transparent'

I had to do this too. 

`backgroundColor: transparent` did not work for me. Thank you for sharing this fix.

`"react-native-signature-canvas": "^4.7.2",`
