### ISSUE TITLE
autoClear @1.7.1 doesn't seem to work on Expo

### ISSUE THREAD

**Issue by MarkeyMarke** [YanYuanFE/react-native-signature-canvas#31]
I've tried installing the new 1.7.1 build via NPM. Does the new build work on Expo as well? I currently have my component rendering like this:

```
    <View>
      <Signature
        key={value}
        // handle when you click save button
        onOK={img => console.log(img)}
        onEmpty={() => {}}
        // description text for signature
        descriptionText="Your answer"
        // clear button text
        clearText="Clear"
        // save button text
        confirmText="Send"
        autoClear={true}
      />
    </View>
```

But it doesn't seem to reset the canvas when I click send. I also made sure to check my dependencies and I do have the newest version:

```
"dependencies": {
    "expo": "~36.0.0",
    "expo-image-picker": "^8.0.2",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-signature-canvas": "^1.7.1",
    "react-native-svg": "9.13.3",
    "react-native-web": "~0.11.7",
    "rn-draw": "0.0.6"
  },
```

Perhaps I've done something wrong?

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/exampleApp,
you can try this example, expo v36 has not test.

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expo-app,

add expo v36 example, work fine.
