### ISSUE TITLE
Not able to make vertical lines or full signature but horizontal lines are working fine

### ISSUE THREAD

**Issue by Akshaybagai52** [YanYuanFE/react-native-signature-canvas#319]
import React, { useRef } from 'react';
import { View, StyleSheet, Button } from 'react-native';
import SignatureCanvas, { SignatureViewRef } from 'react-native-signature-canvas';

export const MySignatureCanvas: React.FC = () => {
  const signatureRef = useRef<SignatureViewRef>(null); // Create a ref for the signature canvas

  const handleClearSignature = () => {
    signatureRef.current?.clearSignature();
  };

  const handleGetSignature = () => {
    const signatureData = signatureRef.current?.getData();
    console.log(signatureData);
  };

  return (
    <View >
      <SignatureCanvas
      androidHardwareAccelerationDisabled={true}
        ref={signatureRef}
        scrollable={false} // Disable scrolling
        // backgroundColor="#000"
        maxWidth={3}
        style={styles.canvas}
      />
      <View style={styles.buttonsContainer}>
        <Button title="Clear Signature" onPress={handleClearSignature} />
        <Button title="Get Signature Data" onPress={handleGetSignature} />
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  canvas: {
    borderWidth: 1,
    borderColor: '#000000',
    width: '90%',
    height: 300, // Increase the height for more drawing space
  },
  buttonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 20,
  },
});

**Comment by Akshaybagai52** [comment]
Above one is full code for signature screen whenever i'm drawing vertical line then i'm getting dots on screen but whenever i'm drawing horizontal lines then it is working fine 
is there any issue ?

**Comment by YanYuanFE** [comment]
you can use scrollEnabled props in the ScrollView, when onBegin triggered you can set scrollEnabled with false, when onEnd triggered you can set scrollEnabled with true
same with https://github.com/YanYuanFE/react-native-signature-canvas/issues/11#issuecomment-643923851
