### ISSUE TITLE
Update Peer Dependency with Webview

### ISSUE THREAD

**Issue by YusufRSU** [YanYuanFE/react-native-signature-canvas#321]
Recently got a message from google that all new apps and app updates need to be targeting APK33 starting august 31, 2023

the react native webview package is only compatible with APK33 after version 11.22.7, the peer dependency here is 11.18.1

let me know if I've misunderstood something, but it seems like the dependency on this project will need to be updated

**Comment by YanYuanFE** [comment]
4.6.1 updated

**Comment by YusufRSU** [comment]
Thank You
