### ISSUE TITLE
I cannot see what i'm drawing on android

### ISSUE THREAD

**Issue by yepes** [YanYuanFE/react-native-signature-canvas#329]
Hi
I have created a small demo because I cannot have this library to work on android <31. The same code works on api 31, 32, 33 and 34.

The thing is that I cannot see what is being draw, but the data is there. This is on an emulator API 31:
<img width="449" alt="image" src="https://github.com/YanYuanFE/react-native-signature-canvas/assets/1114453/62902de4-c147-47e7-9d62-a2c4bdcc3633">

This is the same on API 28:
<img width="477" alt="image" src="https://github.com/YanYuanFE/react-native-signature-canvas/assets/1114453/0ae0bed6-85a0-4788-9b99-8932b2356699">

As you can see, the data signature is there, you just can see it.

This is what I have in my package.json:
"react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-signature-canvas": "^4.6.1",
    "react-native-webview": "^13.6.0"

It's a bare RN project. 

I created a repro repo here:
https://github.com/yepes/signaturepad-demo

**Comment by kvnlnt** [comment]
same

**Comment by yepes** [comment]
I managed to test it on an real device on android api 29 and work on the real device, but de behaviour on the emulator is the described above

**Comment by YanYuanFE** [comment]
Sorry to keep you waiting. After this period of troubleshooting, I have determined the cause of the problem and released a new version to fix it.

npm i react-native-signature-canvas@4.7.1

and then,

set props androidLayerType to 'software' for fix it

<SignatureScreen
              androidLayerType={'software'}/>

**Comment by yepes** [comment]
@YanYuanFE I can confirm it works. The signature on android is not as crisp as in iOS, but yeah, it works.

Thanks
