### ISSUE TITLE
[Feature] Forward onLoadEnd property up

### ISSUE THREAD

**Issue by Justin-Singh125125** [YanYuanFE/react-native-signature-canvas#330]
## Feature Request - Forward onLoadEnd Property

**Description**
I would like to request the addition of a feature that allows the forwarding of the `onLoadEnd` property. This enhancement would enable developers to have improved control over their loading state handling by allowing them to define their own `onLoadEnd` callback instead of relying solely on the internal loading state management.

**Why is this feature beneficial?**
With the addition of this property, developers can manage their own loading states. For example, we can give developers the power to display custom loading images.

**Additional context***
We can keep the default internal state, but now developers can override it if they wish.

![image](https://github.com/YanYuanFE/react-native-signature-canvas/assets/41179777/27f557d1-8ebf-4ca8-b6b8-fe802283c2d5)

**Comment by HectorZR** [comment]
I have the same issue. It would be awesome to have this implemented!

**Comment by EvanYan1024** [comment]
received

**Comment by YanYuanFE** [comment]
received

**Comment by YanYuanFE** [comment]
4.7.0 released！

**Comment by Justin-Singh125125** [comment]
Awesome! Thank you so much😊
