### ISSUE TITLE
Get signature as SVG. 

### ISSUE THREAD

**Issue by mpkelly** [YanYuanFE/react-native-signature-canvas#34]
Hello, 

Are you able to update the API so that SVG signature export is possible? These are supported in the wrapped component already. 

Thanks
Mike

**Comment by YanYuanFE** [comment]
svg can be exported in the following format，svg can be exported, the format is as follows, but the question is, how to display this svg in react native or expo。
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMzY4IDMzMC42NjY2NjY2NjY2NjY3IiB3aWR0aD0iMzY4IiBoZWlnaHQ9IjMzMC42NjY2NjY2NjY2NjY3Ij48cGF0aCBkPSJNIDEzOS4xNDMsOTcuMjM4IEMgMTQ0LjY3Niw5My40MjIgMTQ0Ljc3NCw5My41ODIgMTUwLjQwNiw4OS45MjciIHN0cm9rZS13aWR0aD0iMy45OTMiIHN0cm9rZT0iYmxhY2siIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCI+PC9wYXRoPjxwYXRoIGQ9Ik0gMTUwLjQwNiw4OS45MjcgQyAxNTguMDA4LDg0LjgzOCAxNTguMTY4LDg1LjE5MSAxNjYuMTI4LDgwLjc3NiIgc3Ryb2tlLXdpZHRoPSIyLjkzMiIgc3Ryb2tlPSJibGFjayIgZmlsbD0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIj48L3BhdGg+PHBhdGggZD0iTSAxNjYuMTI4LDgwLjc3NiBDIDE3NS4xNzcsNzUuOTI5IDE3NS4xODIsNzYuMjQ4IDE4NC43NTMsNzIuNzQ2IiBzdHJva2Utd2lkdGg9IjIuNjY1IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE4NC43NTMsNzIuNzQ2IEMgMTkyLjI0Myw2OS45NDAgMTkyLjAwNCw3MC4zMzYgMTk5Ljc4Myw2OS41OTAiIHN0cm9rZS13aWR0aD0iMi45MTQiIHN0cm9rZT0iYmxhY2siIGZpbGw9Im5vbmUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCI+PC9wYXRoPjxwYXRoIGQ9Ik0gMTk5Ljc4Myw2OS41OTAgQyAyMDYuODE1LDY4LjYyMCAyMDUuNDc4LDY5LjMyNiAyMTEuMjIyLDcxLjUxNyIgc3Ryb2tlLXdpZHRoPSIzLjIwMiIgc3Ryb2tlPSJibGFjayIgZmlsbD0ibm9uZSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIj48L3BhdGg+PHBhdGggZD0iTSAyMTEuMjIyLDcxLjUxNyBDIDIxNi43ODcsNzUuNzcyIDIxNS4zNTgsNzQuMjM2IDIxNi44NjksODAuODI0IiBzdHJva2Utd2lkdGg9IjMuMzAyIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIxNi44NjksODAuODI0IEMgMjE2LjI4NCw5MS42NzEgMjE3LjAyMiw5MC4yNzggMjExLjY5MCwxMDAuNTI4IiBzdHJva2Utd2lkdGg9IjIuNzQ0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIxMS42OTAsMTAwLjUyOCBDIDIwNC40NDYsMTEwLjE5OSAyMDYuMjQ1LDExMS4wMjYgMTk2Ljc5MSwxMTkuNTMzIiBzdHJva2Utd2lkdGg9IjIuNTUxIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE5Ni43OTEsMTE5LjUzMyBDIDE4OC42MjAsMTI4Ljk4OCAxODguODY4LDEyOS4xOTIgMTgwLjUzNCwxMzguNTE0IiBzdHJva2Utd2lkdGg9IjIuMjkxIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE4MC41MzQsMTM4LjUxNCBDIDE3NC4wOTMsMTQ1LjU4NCAxNzQuMzYzLDE0NS43ODMgMTY4LjI3NywxNTMuMTIzIiBzdHJva2Utd2lkdGg9IjIuNDc3IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE2OC4yNzcsMTUzLjEyMyBDIDE2NC40NjEsMTU3LjU1NCAxNjQuODI0LDE1Ny41OTggMTYxLjk5NSwxNjIuNTQxIiBzdHJva2Utd2lkdGg9IjIuOTk4IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE2MS45OTUsMTYyLjU0MSBDIDE1OS42OTUsMTY2LjE3NiAxNjAuNzc3LDE2NS4wMDcgMTYwLjkwNywxNjguMDMwIiBzdHJva2Utd2lkdGg9IjMuNzMxIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE2MC45MDcsMTY4LjAzMCBDIDE2NC4wMzIsMTcwLjk3NiAxNjIuNTE3LDE3MC40OTEgMTY3LjY0MSwxNzEuMTcxIiBzdHJva2Utd2lkdGg9IjMuOTQ0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE2Ny42NDEsMTcxLjE3MSBDIDE3Ny40MjYsMTcwLjg0NiAxNzcuMTA3LDE3MS42ODEgMTg3LjA1NiwxNjkuNDM4IiBzdHJva2Utd2lkdGg9IjIuOTgzIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE4Ny4wNTYsMTY5LjQzOCBDIDE5Ny42NTIsMTY3LjE0MCAxOTcuNzYzLDE2Ny44NzIgMjA4LjMxMywxNjUuMjIxIiBzdHJva2Utd2lkdGg9IjIuNTQxIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIwOC4zMTMsMTY1LjIyMSBDIDIxNS41ODMsMTYzLjQ2NyAyMTUuNTY0LDE2My45MTYgMjIyLjg4MSwxNjIuOTkwIiBzdHJva2Utd2lkdGg9IjIuODU0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIyMi44ODEsMTYyLjk5MCBDIDIyOC45NTIsMTYxLjQ4OCAyMjYuNTQzLDE2Mi43NTEgMjMwLjIzMywxNjMuNzg3IiBzdHJva2Utd2lkdGg9IjMuNTYzIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIzMC4yMzMsMTYzLjc4NyBDIDIzMS42ODEsMTY5Ljk0OCAyMzIuMDEwLDE2Ni45NzUgMjI4Ljk5NiwxNzMuOTY1IiBzdHJva2Utd2lkdGg9IjQuMDI0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIyOC45OTYsMTczLjk2NSBDIDIyMi4zNTMsMTgwLjgyOCAyMjQuMDI0LDE4MS40MDMgMjE0LjkxOSwxODYuNjk4IiBzdHJva2Utd2lkdGg9IjIuOTU5IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIxNC45MTksMTg2LjY5OCBDIDIwNS41OTUsMTkzLjAwOCAyMDYuMTA0LDE5My42NTkgMTk2LjQ5NywxOTkuNjI3IiBzdHJva2Utd2lkdGg9IjIuNTYwIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE5Ni40OTcsMTk5LjYyNyBDIDE4OS4zMzAsMjA1LjAwOCAxODkuMjUxLDIwNC44OTggMTgyLjIyOSwyMTAuNDc4IiBzdHJva2Utd2lkdGg9IjIuNjI0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE4Mi4yMjksMjEwLjQ3OCBDIDE3NS44MDgsMjE0LjcyNyAxNzYuMjEyLDIxNS4xMTMgMTcwLjI2MiwyMTkuODM1IiBzdHJva2Utd2lkdGg9IjIuODU3IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE3MC4yNjIsMjE5LjgzNSBDIDE2NC4zNTcsMjI1LjU4MSAxNjcuNzgzLDIyMi4xMTkgMTY2LjE3OSwyMjUuMjYyIiBzdHJva2Utd2lkdGg9IjMuOTA5IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE2Ni4xNzksMjI1LjI2MiBDIDE3NS43NDYsMjIxLjg0MiAxNzEuNTk3LDIyNC4zMTQgMTg0Ljc0MywyMTcuMzAwIiBzdHJva2Utd2lkdGg9IjMuNTc1IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDE4NC43NDMsMjE3LjMwMCBDIDE5Mi42NjQsMjEyLjYxMyAxOTIuOTQyLDIxMy4xNjEgMjAwLjU3MCwyMDcuOTAwIiBzdHJva2Utd2lkdGg9IjIuOTc5IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIwMC41NzAsMjA3LjkwMCBDIDIwNC4yNjYsMjA1LjQ5NCAyMDQuMzQ5LDIwNS42NDcgMjA4LjExNCwyMDMuMzY5IiBzdHJva2Utd2lkdGg9IjMuNDU0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIwOC4xMTQsMjAzLjM2OSBDIDIxMC41MTcsMjAxLjI2MiAyMTAuNTYyLDIwMi4wMTcgMjEzLjE2MSwyMDAuOTQ2IiBzdHJva2Utd2lkdGg9IjMuOTY0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIxMy4xNjEsMjAwLjk0NiBDIDIxNi41ODksMjAwLjY5OSAyMTYuMDU1LDIwMC42MDEgMjE5LjE5MCwyMDIuMDQ4IiBzdHJva2Utd2lkdGg9IjQuNDkzIiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48cGF0aCBkPSJNIDIxOS4xOTAsMjAyLjA0OCBDIDIyMS4zMjksMjA0LjI1NCAyMjEuNzk2LDIwMy4zOTkgMjIzLjU3NSwyMDYuMzQ2IiBzdHJva2Utd2lkdGg9IjQuMjM0IiBzdHJva2U9ImJsYWNrIiBmaWxsPSJub25lIiBzdHJva2UtbGluZWNhcD0icm91bmQiPjwvcGF0aD48L3N2Zz4=

**Comment by mpkelly** [comment]
Hi @YanYuanFE, do you mean SVG is already supported? It looks like you're only sending PNG with  `onOK`. 

As for displaying the SVG data URL, I don't need to do this. I want to embed the signature into a PDF document and this will be done on the server. I need SVG so that the signature scales with the PDF without pixelating. I am currently using `react-native-signature-pad` but will switch to this project if/when SVG is supported.

**Comment by YanYuanFE** [comment]
support svg need update signature_pad.js, I need update  an version.

**Comment by YanYuanFE** [comment]
v1.9.0 has published, thanks your suggestion. for example:
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expo-app

**Comment by mpkelly** [comment]
Thank you @YanYuanFE!
