### ISSUE TITLE
Is react-native-signature-canvas compatible with expo web mode? 

### ISSUE THREAD

**Issue by agustif** [YanYuanFE/react-native-signature-canvas#35]
If i try any examples to run on expo web I get an infinite loading state and nothing else. what might I be doing wrong?

**Comment by YanYuanFE** [comment]
Sorry，Currently it does not support running on expo web。

**Comment by agustif** [comment]
It works fine in iOS / Android, but I can't get it to work for --web mode, would it be easy to make compatible as I'm looking to deploy to web mainly but I would like to use this lib for when I go full installed app in ios/android later down the implementation.

Thanks!

<img width="1459" alt="Captura de pantalla 2020-03-30 a las 15 39 15" src="https://user-images.githubusercontent.com/6601142/77918870-c55ea400-729c-11ea-99b7-c94004e921b1.png">

**Comment by YanYuanFE** [comment]
You can try to be compatible with the web platform in your application. Use different libraries by judging the platform. When running on the web, use https://github.com/szimek/signature_pad。

**Comment by YanYuanFE** [comment]
For the time being I do n’t have time to do compatibility, I will consider later, thank you for your suggestions。

**Comment by agustif** [comment]
Thanks @YanYuanFE I've had luck using this other react library for expo-web https://www.npmjs.com/package/react-signature-canvas

I guess this can be closed, thanks for your help again!
