### ISSUE TITLE
Not Working in Nexus 5 (Android 6.0.1)

### ISSUE THREAD

**Issue by SruthiSNair** [YanYuanFE/react-native-signature-canvas#4]
My basic signature app is not working in Nexus 5 Anroid 6.0.1 OS. Its working fine in other devices .

**Comment by YanYuanFE** [comment]
Can you provide some error info？

**Comment by SruthiSNair** [comment]
Actually its not showing any error . The problem is , drawing is not working with this device.

**Comment by SruthiSNair** [comment]
@YanYuanFE 
Actually its not showing any error . The problem is , drawing is not working with this device.

**Comment by SruthiSNair** [comment]
@YanYuanFE  Actually no such error occured  . The problem is , cant able to draw the signature with this device .

**Comment by YanYuanFE** [comment]
It seems to be related with the WebView. This component uses WebView, and support for WebView by different devices may affect its compatibility.
