### ISSUE TITLE
Error when adding the import

### ISSUE THREAD

**Issue by dierke9** [YanYuanFE/react-native-signature-canvas#40]
The moment I add the import i get the following error:
`Error: Unable to resolve module `./debugger-ui/debuggerWorker.d9da4ed7` from ``:`

Using version 2.0.0 Expo 37

EDIT: Also tried version 1.9.0 wth the same result

**Comment by dierke9** [comment]
After some deeper search I have found the problem in the end.

The problem was the fact that i had react-native-webview as one of my own node-modules.
In your package you also install this seperatly instead of refering to the original node-modules folder like others. This caused it to register twice, remove the mode from my package resolved the problem.

**Comment by YanYuanFE** [comment]
OK, thank you for your support.
