### ISSUE TITLE
signature loss

### ISSUE THREAD

**Issue by Aishwaryashetty** [YanYuanFE/react-native-signature-canvas#42]
The signature disappears on the change of orientation.

**Comment by YanYuanFE** [comment]
Currently does not support landscape screen, will be considered compatible in the future

**Comment by Aishwaryashetty** [comment]
I can sign in landscape n portrait, but when I change from landscape to portrait or visa versa, due to dimension change the signature is cleared.

**Comment by YanYuanFE** [comment]
Can you provide a working code example？

**Comment by zengqinghua1** [comment]
I also encountered a similar problem. When the keyboard of the page popped up, the content of the signed version was cleared. How can this be solved?

**Comment by YanYuanFE** [comment]
expo version?react-native-signature-canvas version? code example?

**Comment by zengqinghua1** [comment]
I did not use Expo to create a project, I used a project created by yarn
 "react-native-signature-canvas": "^1.9.0"
<Signature
              onOK={this.handleSignature}
              onEmpty={this.handleEmpty}
              descriptionText=""
              clearText="Clear"
              confirmText="Save"
              webStyle={style}
              style={{ marginTop: 10 }}
            />

**Comment by YanYuanFE** [comment]
> I did not use Expo to create a project, I used a project created by yarn
> "react-native-signature-canvas": "^1.9.0"
> <Signature
> onOK={this.handleSignature}
> onEmpty={this.handleEmpty}
> descriptionText=""
> clearText="Clear"
> confirmText="Save"
> webStyle={style}
> style={{ marginTop: 10 }}
> />

Are you use react-native-cli init project?

**Comment by zengqinghua1** [comment]
Yes, how to solve this problem

**Comment by YanYuanFE** [comment]
How to reproduce this problem？sign page has not keyboard. you sign page has Input?

**Comment by zengqinghua1** [comment]
<TextInput
          ref={(view)=>this.inputText = view}
            editable={this.state.isEdit}
            style={styles.inupt}
            onChangeText={(inputData) => {
              // this.setState({ signName: inputData })
              this.inputText.setNativeProps({
                signName: inputData
            });
            }} >{this.state.signName}</TextInput>
<Signature
onOK={this.handleSignature}
onEmpty={this.handleEmpty}
descriptionText=""
clearText="Clear"
confirmText="Save"
webStyle={style}
style={{ marginTop: 10 }}
/>


I added an input box component above the signed component

**Comment by YanYuanFE** [comment]
"react-native-signature-canvas": "^2.2.0" has fixed this problem.

**Comment by zengqinghua1** [comment]
Thank you very much for your modification.
But there is still a small problem, why does the signature board tremble when the keyboard pops up or retracts?

**Comment by YanYuanFE** [comment]
Signature is a Canvas of webview, when the keyboard pops up, window has been resize, canvas size has been change.

**Comment by oohajadya** [comment]
> I can sign in landscape n portrait, but when I change from landscape to portrait or visa versa, due to dimension change the signature is cleared.

**Comment by viswaKyro** [comment]
> The signature disappears on the change of orientation.

Able to fix this issue? I am using react-native-signature-canvas: 4.5.0.
