### ISSUE TITLE
Cannot update descriptiontext with hooks

### ISSUE THREAD

**Issue by aik117** [YanYuanFE/react-native-signature-canvas#43]
I am uploading the signature to server and i want to update the description text when it is uploaded successfully. However i cannot do this once a text has been added, it is not updating with setState. Please help. This is my code

    `import React, { useState } from "react";
    import { View, StyleSheet } from "react-native";
    import Signature from "react-native-signature-canvas";
    import { colorStyles } from "../../../css/AppStyles";
    import { requestData } from "../../../Api/ApiRequests";
    import { UPDATE_SIGNATURE_URL } from "../../../Config/Routes";
    import "../../../Utils/Globals";
    import Toast from "react-native-simple-toast";
    import moment from "moment";
    import Loader from "react-native-modal-loader";

    const SignatureScreen = (props) => {

    const [showLoader, setShowLoader] = useState(false);

    //getting the passed values from previous screen through props
    let signatureInfo = props.navigation.state.params.signatureInfo;

    const [signedOnTime, setSignedOnTime] = useState(signatureInfo.signdate);

    const [d, setD] = useState("abc");
    
    const updateSignature= (image) => {
        setShowLoader(true);

        let obj = {};
        obj.employeeId = CLIENT_ID;
        obj.operatorID = OPERATOR_ID;
        obj.serviceid = signatureInfo.serviceId;
        obj.deliveryid = signatureInfo.deliveryID;
        obj.signatureimagebase64 = image;
        
        requestData(PROVIDER_URL + UPDATE_SIGNATURE_URL, "POST", obj).then((result) => { 
            if (result.status == "Successful") {
                const date = moment().format("DD/MM/YYYY");
                setSignedOnTime(date);
                setD("def");
                setTimeout(() => {
                    Toast.show(result.message, Toast.SHORT);
                }, 1000);
            }
            else {
                setTimeout(() => {
                    Toast.show(result.message ?result.message :result, Toast.SHORT);
                }, 1000);
            }
            setShowLoader(false);
        })
        .catch((error) => {
            setTimeout(() => {
                Toast.show(error, Toast.SHORT);
            }, 1000);
            setShowLoader(false);
        });
    }
 
    return (
        <View style = {{ flex : 1 }}>
            <Loader loading = { showLoader } />
            <Signature
                // handle when you click save button
                onOK = { (img) => { updateSignature(img) } }
                onEmpty = { () => Toast.show("No signature", Toast.SHORT) }
                // description text for signature
                descriptionText = { "Signed On : " + d }
                // clear button text
                clearText = "Clear"
                // save button text
                confirmText = "Save"
                // String, webview style for overwrite default style, all style: https://github.com/YanYuanFE/react-native-signature-canvas/blob/master/h5/css/signature-pad.css
                webStyle = { 
                    `.m-signature-pad--footer
                        .description {
                            color : #000000;
                        }
                    .m-signature-pad--footer
                        .button {
                            background-color : ${ colorStyles.headerColor };
                            color : #FFFFFF; 
                        }`
                }
                //autoClear = { true }
            />
        </View>
    );
    }

    const styles = StyleSheet.create({});

    export default SignatureScreen;`

**Comment by YanYuanFE** [comment]
"react-native-signature-canvas": "^2.1.0" has fixed this problem.

**Comment by aik117** [comment]
@YanYuanFE i've done a workaround for this. I disabled the descriptiontext and added another view at the bottom and i am updating that view with hooks when signature is uploaded successfully. Once i try again with latest version i'll let you know. Thanks.

**Comment by YanYuanFE** [comment]
OK, Thanks。
