### ISSUE TITLE
Display provided image on load

### ISSUE THREAD

**Issue by xming13** [YanYuanFE/react-native-signature-canvas#45]
Hi, it will be good if there is a feature to allow passing an image via prop and the canvas will display the image on load.

**Comment by YanYuanFE** [comment]
OK, good idea.

**Comment by YanYuanFE** [comment]
v2.5.0 has been released.

**Comment by ahmed-abdelkader-dev** [comment]
Hello,
I tried passing a base64 string to the dataURL but nothing is loaded into canvas

**Comment by YanYuanFE** [comment]
> Hello,
> I tried passing a base64 string to the dataURL but nothing is loaded into canvas

Please provide version and env info. and code example
