### ISSUE TITLE
Get image as a png or jpeg saved temporarily to the device.

### ISSUE THREAD

**Issue by anantshukla** [YanYuanFE/react-native-signature-canvas#47]
Thank you so much. Finally, a good signature capture library that works perfectly.
Is there any possible way I can save the image to the device. Actually, I need to upload a png or jpeg to the server. Something similar to what react-native camera does.
I require the png/jpeg and not the base64 format.
Is there any way to do this. Thank you so much!

**Comment by YanYuanFE** [comment]
Are you using expo or react-native-cli?

**Comment by YanYuanFE** [comment]
react-native-signature itself only provides base64 pictures. If you need to save base64 pictures as local files, expo users can use expo-file-system, react-native-cli users can use react-native-fs, thank you.
expo like this example:
https://github.com/YanYuanFE/react-native-signature-canvas/blob/master/example/expo-app/App.js

**Comment by anantshukla** [comment]
> react-native-signature itself only provides base64 pictures. If you need to save base64 pictures as local files, expo users can use expo-file-system, react-native-cli users can use react-native-fs, thank you.
> expo like this example:
> https://github.com/YanYuanFE/react-native-signature-canvas/blob/master/example/expo-app/App.js

Thank you so much! Will try!
