### ISSUE TITLE
SignatureScreen reset after signed

### ISSUE THREAD

**Issue by MarcoPilolli** [YanYuanFE/react-native-signature-canvas#48]
Hi,
i'm a newbie on react native
i'm trying to use readSignature using the example...

but when i finished to sign the screen reset

`import SignatureScreen from 'react-native-signature-canvas';
 
const Sign = ({text, onOK}) => {
  const ref = useRef();
 
  const handleSignature = signature => {
   setFirma(signature);
  };
 
  const handleEmpty = () => {
    console.log('Empty');
  }
 
  const handleClear = () => {
    console.log('clear success!');
  }
 
  const handleEnd = () => {
      ref.current.readSignature();
  }
 
  return (
    <SignatureScreen
        ref={ref}
        onEnd={handleEnd}
        onOK={handleSignature} 
        onEmpty={handleEmpty}
        onClear={handleClear}
        autoClear={true} 
        descriptionText={text}
    />
  );
}
 
export default Sign;
`
setFirma is: const [firma,setFirma] = useState('');

**Comment by MarcoPilolli** [comment]
my goal is to save the signature without confirm it, thanks

**Comment by YanYuanFE** [comment]
```
return (
    <SignatureScreen
        ref={ref}
        onEnd={handleEnd}
        onOK={handleSignature} 
        onEmpty={handleEmpty}
    />
  );
```

**Comment by MarcoPilolli** [comment]
don't work

after i signed refresh and i loose the sign

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/blob/master/example/expo-app/App.js,
You can try this example, It's work fine.
