### ISSUE TITLE
Not working when build

### ISSUE THREAD

**Issue by adrianojfg** [YanYuanFE/react-native-signature-canvas#5]
The component works great in Expo, but when I build for android and install the apk, the component stop working and the screen stays gray. Any suggestions?

**Comment by NoSaBo** [comment]
Did it worked with the debug-apk? Maybe we can see the error output and help you out.

**Comment by adrianojfg** [comment]
Good idea. I will build the debug-apk. In addition, I was using the API 28 Android emulator when works great with Expo and when I installed the expo build apk too. However, when I downgraded to API 26, even in Expo, it's not possible to draw the signature, clean or save it. Unfortunately, there is no error/warning message when I try to draw, clean or save.

**Comment by adrianojfg** [comment]
Digging a little bit it seems to be related with the WebView. Samsung smartphones with Chrome 72 version is not working, but Motorola smartphone with Chrome 71 is working. So, I'll close this issue because it's not related with the Signature component itself.
