### ISSUE TITLE
Can't sign if signature is in a ScrollView?

### ISSUE THREAD

**Issue by isocra** [YanYuanFE/react-native-signature-canvas#50]
Hi YanYuan,

I need to capture 5 signatures and they don't all fit on the screen, so I've put them in a `ScrollView`. The problem is that now I can't sign any more because any vertical movement of my finger is sent to the ScrollView.

Is there a way to get the Signature component to capture these gestures and not pass them on?

Thanks

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/issues/11

**Comment by YanYuanFE** [comment]
same issue. you can try it.

**Comment by isocra** [comment]
This works https://github.com/YanYuanFE/react-native-signature-canvas/issues/11#issuecomment-643923851
