### ISSUE TITLE
HandleSignature not work on IOS

### ISSUE THREAD

**Issue by mehmetisitan** [YanYuanFE/react-native-signature-canvas#6]
Hi,
onOK property(handleSignature function) works on Android but not work on IOS. Please help me.

`<Signature
                        onOK={this.handleSignature}
                        descriptionText={this.props.navigation.getParam('ciftciAdSoyad', '0')}
                        clearText="Temizle"
                        confirmText={this.state.imzaVar ? "Güncelle" : "Kaydet"}
                        webStyle={style}
                    />`

`handleSignature = signature => {
        console.log("Signature:" + signature)
    };`

**Comment by YanYuanFE** [comment]
Do you use Expo init project?

**Comment by mehmetisitan** [comment]
Yes I using Expo init project.

**Comment by YanYuanFE** [comment]
Can you provide a demo to show you problem?

**Comment by mehmetisitan** [comment]
Actually the problem is clear. Not enter onOK (handleSignature) function. Click on save button nothing happened. I give you a Ammy connection for see the problem. Please send a mail me. mehmetisitann@gmail.com

**Comment by YanYuanFE** [comment]
I would like to have as compact a code as possible or a link of the GitHub repository.

**Comment by mehmetisitan** [comment]
This is my render.

`render() {
        const style = `.m-signature-pad--footer
        .button {
          background-color: red;
          color: #FFF;
        }`;
        return (
            <Container style={styles.container} style={{ marginTop: Constants.statusBarHeight }}>
                <Header>
                    <Left>
                        <Button
                            transparent
                            onPress={() => this.props.navigation.openDrawer()}
                        >
                            <Icon name="ios-menu" />
                        </Button>
                    </Left>
                    <Body>
                        <Title>{this.props.navigation.getParam('ciftciAdSoyad', '0')}</Title>
                        <Subtitle>İmza</Subtitle>
                    </Body>
                    <Right>
                        <Button
                            transparent
                            onPress={() => this.props.navigation.goBack()}>
                            <Icon name="md-arrow-round-back" />
                        </Button>
                    </Right>
                </Header>

                <View style={{ flex: 1 }}>
                    {
                        this.state.imzaVar ?
                            <View style={styles.preview}>
                                <Image
                                    resizeMode={"contain"}
                                    style={{ width: 335, height: 114 }}
                                    source={{ uri: this.state.imza }}
                                />
                            </View>
                            :
                            null
                    }

                    <Signature
                        onOK={this.handleSignature}
                        descriptionText={this.props.navigation.getParam('ciftciAdSoyad', '0')}
                        clearText="Temizle"
                        confirmText={this.state.imzaVar ? "Güncelle" : "Kaydet"}
                        webStyle={style}
                    />
                </View>
            </Container>
        );
    }`

And this is my onOK function. But this function doesn't work on IOS. Doesn't enter this function.

`handleSignature = signature => {
        Alert.alert("Notice", "Enter Here??")
        console.log("incoming signature is:" + signature)
    };`

**Comment by YanYuanFE** [comment]
I hope that you can provide a minimal project that can be run to reproduce your problem.
for example, https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/exampleApp。

**Comment by YanYuanFE** [comment]
Sorry,I have recreated this problem and need some time to process it. It seems that the expo update version is causing this problem. You can try the old version of expo.

**Comment by mehmetisitan** [comment]
> Sorry,I have recreated this problem and need some time to process it. It seems that the expo update version is causing this problem. You can try the old version of expo.

Thanks, In which version does it work properly?

**Comment by YanYuanFE** [comment]
"expo": "^28.0.0-rc.2", this version can work。

**Comment by YanYuanFE** [comment]
I have solved this problem and released the v1.4.0 version.more detail,please see this issue:https://github.com/expo/expo/issues/3168

**Comment by mehmetisitan** [comment]
> I have solved this problem and released the v1.4.0 version.more detail,please see this issue:[expo/expo#3168](https://github.com/expo/expo/issues/3168)

Thanks. This solved the problem.

**Comment by RickyWooo** [comment]
Greetings, I have tried to downgrade to 31.0.0 and already checked the version as  v1.4.0
but it did not work for me.
Any Idea to solve this issue?

**Comment by YanYuanFE** [comment]
> Greetings, I have tried to downgrade to 31.0.0 and already checked the version as v1.4.0
> but it did not work for me.
> Any Idea to solve this issue?

you can use the latest version of expo, and you can run the example of this repo.
example: https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expoApp.
if you still did not work, please report you error and attach some image of error. Thank you for your attention。
