### ISSUE TITLE
Black image

### ISSUE THREAD

**Issue by erikhu** [YanYuanFE/react-native-signature-canvas#60]
when a save the image, it's black. does it passed before? it's me first time with this lib, i tried many ways but all shows the same black image 
![black](https://user-images.githubusercontent.com/7550327/87833565-c4eb1880-c84d-11ea-9912-422413a60be1.png)

**Comment by erikhu** [comment]
i found out the reason, it's for the imagetype prop, the imageType='image/jpeg' it's no functional, that's the reason for black image

**Comment by BlerasKRT** [comment]
you can change it, but ot directly.
