### ISSUE TITLE
How can I set up the background color of the signature picture as a image file.

### ISSUE THREAD

**Issue by BlerasKRT** [YanYuanFE/react-native-signature-canvas#61]
I need to save the picture and I want to have a background pure white. I see that you can changeit in the signature pad where this is based. Any alternative diferent of change directly signature pad code?

**Comment by YanYuanFE** [comment]
background default is white, you can change props of **WebStyle**,
```
webStyle={`.m-signature-pad--body
    canvas {
      background-color: red;
    }`
  }
```

**Comment by BlerasKRT** [comment]
Thank you for the quick response, It works to change the background color of where you paint, but I need that the final image have a diferent background color, not just black...
basically I just change the value of this: at signature_pad.js in function SignaturePad:

this.backgroundColor = options.backgroundColor || 'rgba(0,0,0,0)'; should be 'rgb(255,255,255)'

Thank you in advance.

**Comment by YanYuanFE** [comment]
@BlerasKRT ,v3.1.0 has release, add penColor and backgroundColor props.

**Comment by BlerasKRT** [comment]
Sorry but it does not work in any way...

<Signature
            // handle when you click save button
            onOK={(img) => {
              console.log("img", img);
              props.setTestDrop(img);
            }}
            onEmpty={() => {
              console.log("empty");
              setTestType("empty");
            }}
            // description text for signature
            descriptionText="Firma"
            // clear button text
            clearText="Borrar"
            // save button text
            confirmText="Salvar"
 
            webStyle={`.m-signature-pad--footer
              .button {
                background-color: rgba(255,117,2,1);
                color: #FFF;
            }`}
            autoClear={true}
            imageType={"image/jpeg"}
            backgroundColor="rgb(255,255,255)"
            penColor={"rgba(255,117,2,1)"}
          />

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/91580848-44592500-e980-11ea-8dd4-29a3fc30261d.png)
Oh, work fine on ios.

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expo-app, I use this example

**Comment by BlerasKRT** [comment]
yes working fine in both
