### ISSUE TITLE
backgroundColor and penColor not working in VSCode

### ISSUE THREAD

**Issue by ProxyLeech** [YanYuanFE/react-native-signature-canvas#64]
Hello I have installed react-native-signature-canvas based on the instruction

However it seems like SignatureScreen import isnt taking in effect as the pencolour and backgroundcolor is still in default, despite changing it and viewing it in expo

_module "c:/Users/test/Downloads/react-native-signature-canvas-master/example/expo-app/node_modules/react-native-signature-canvas/index"
Could not find a declaration file for module 'react-native-signature-canvas'. 'c:/Users/micha/Downloads/react-native-signature-canvas-master/example/expo-app/node_modules/react-native-signature-canvas/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-native-signature-canvas` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-signature-canvas';`ts(7016)_

Thanks in advance for the troubleshoot

**Comment by YanYuanFE** [comment]
ts example: https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/ts-expo
