### ISSUE TITLE
Error: Unable to open URL

### ISSUE THREAD

**Issue by Simranjeetnayol** [YanYuanFE/react-native-signature-canvas#7]
![Screenshot 2019-05-26 at 1 56 25 AM](https://user-images.githubusercontent.com/19970605/58374333-e60ded00-7f59-11e9-83fc-d4b62bcee8b1.png)

Hye! YanYuanFE, 
When I click on onOk then I'm getting warning....don't know why?

**Comment by YanYuanFE** [comment]
Do you use Expo init project?

**Comment by YanYuanFE** [comment]
I have solved this problem and released the v1.4.0 version.more detail,please see this issue:https://github.com/expo/expo/issues/3168
