### ISSUE TITLE
How can I hide the footer section?

### ISSUE THREAD

**Issue by antonis0610** [YanYuanFE/react-native-signature-canvas#70]
I tried to hide the bottom section and I setup the style like this.
.m-signature-pad--footer
  {
    display: none;
  };

Save and clear button hidden but bottom section are still available now.
Is there any solution to hide the bottom bar?

**Comment by YanYuanFE** [comment]
Hi, @antonis0610 , Please use **WebStyle** props,
```
<SignatureScreen
          ref={ref}
          onEnd={handleEnd}
          onOK={handleSignature} 
          onEmpty={handleEmpty}
          onClear={handleClear}
          onBegin={handleBegin}
          autoClear={false} 
          descriptionText={text}
          backgroundColor="rgb(255,255,255)"
          penColor={"rgba(255,117,2,1)"}
          imageType="image/jpeg"
          webStyle={`.m-signature-pad--footer {
              display: none;
            }`
          }
      />
```
It's work fine.

**Comment by luminousAvocado** [comment]
Hi @YanYuanFE , i did the display: none, and it hides the buttons but it still seems like the footer area is there. When i draw a line down, it stops once it reaches the footer area, but the signature area you can see extends further. Any way i can fix this?

![image](https://user-images.githubusercontent.com/28456419/95112074-52276600-06f5-11eb-8301-e52d2f256111.png)

**Comment by luminousAvocado** [comment]
I hid the footer section and im trying to make the signature area smaller but now it looks like this:

![image](https://user-images.githubusercontent.com/28456419/95120696-c61c3b00-0702-11eb-83bf-beed52c1d646.png)

![image](https://user-images.githubusercontent.com/28456419/95120718-d207fd00-0702-11eb-93f1-02e2fcf1deaf.png)

how can i make that grey area disappear?

**Comment by YanYuanFE** [comment]
@luminousAvocado gray area is body's background

```
body {
              background: none;
            }
```
