### ISSUE TITLE
Adjust The thickness of signature

### ISSUE THREAD

**Issue by darick0029** [YanYuanFE/react-native-signature-canvas#71]
Hi, Thank you for this cool component.
May I please ask if theres any way to increase the weight of the signature so i can adjust it to match with our live site?

This is the thickness on our site: https://prnt.sc/uth55g

while this is what I get when I send signature: https://prnt.sc/uth6b3

**Comment by YanYuanFE** [comment]
v3.2.0, add minSize props for line width.

**Comment by darick0029** [comment]
Great Thank you!!

**Comment by hari3110** [comment]
@YanYuanFE You should add in Readme Doc

**Comment by YanYuanFE** [comment]
> @YanYuanFE You should add in Readme Doc

has add, https://github.com/YanYuanFE/react-native-signature-canvas#properties, **minWidth**

**Comment by YanYuanFE** [comment]
> v3.2.0, add minSize props for line width.

Sorry, no is minSize, is minWidth
