### ISSUE TITLE
custom "Save" button

### ISSUE THREAD

**Issue by luminousAvocado** [YanYuanFE/react-native-signature-canvas#74]
Hi, i've made my own "Save" button and im trying to save the signature but when i console.log the signature, i'm not getting the expected result (base64 string)

![image](https://user-images.githubusercontent.com/28456419/95270777-2093c500-07f1-11eb-8e81-877cd54781c5.png)

![image](https://user-images.githubusercontent.com/28456419/95270761-1a9de400-07f1-11eb-9b32-7d3d744b2fea.png)

**Comment by YanYuanFE** [comment]
```
<Signature
  ref={ref}
  onOK={handleOk}
/>

<TouchableOpacity onPress={() => {ref.current.readSignature}}></TouchableOpacity>
```

**Comment by luminousAvocado** [comment]
`const handleOk = signature => {
        console.log('before');
        console.log(signature);
        console.log('after');
    }

<Signature
                    ref={ref}
                    onOk={handleOk}
                    webStyle={sigWebStyle}
                />

<TouchableOpacity style={styles.saveBtn}>
                        <Text style={[{color: 'white'}, styles.saveClearTxt]} onPress={() => {ref.current.readSignature}}>Ok</Text>
                    </TouchableOpacity>`

**Comment by luminousAvocado** [comment]
Hmm so i tried to following it doesnt seem to be triggering "handleOk", nothing output to console

![image](https://user-images.githubusercontent.com/28456419/95368207-a4e65680-088a-11eb-9705-a44f61acced8.png)

![image](https://user-images.githubusercontent.com/28456419/95368225-ad3e9180-088a-11eb-8d0b-531df8272cf7.png)

![image](https://user-images.githubusercontent.com/28456419/95368261-bf203480-088a-11eb-8edb-9c7de8ebb57d.png)

i tried with and without readSignature() as well

**Comment by hussainarthuna** [comment]
> <Signature
>   ref={ref}
>   onOK={handleOk}
> />
> 
> <TouchableOpacity onPress={() => {ref.current.readSignature}}></TouchableOpacity>

ref.current.readSignature works only if we are handling handleOk.

Thank you this is working fine

**Comment by hussainarthuna** [comment]
> <Signature
>   ref={ref}
>   onOK={handleOk}
> />
> 
> <TouchableOpacity onPress={() => {ref.current.readSignature}}></TouchableOpacity>

ref.current.readSignature works only if we are handling handleOk.

Thank you this is working fine
