### ISSUE TITLE
TargetSdkVersion = 29 did not work properly

### ISSUE THREAD

**Issue by mynameisliuyurong** [YanYuanFE/react-native-signature-canvas#76]
Hello targetSdkVersion= 28 is normal, but Android shows nothing when targetSdkVersion=29.

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/96569030-34fcb500-12fb-11eb-8b97-ec97318cf463.png)

**Comment by YanYuanFE** [comment]
Installation(for React Native V0.5x.x or Expo SDK < v33)
npm install --save react-native-signature-canvas@1.4.2

**Comment by mynameisliuyurong** [comment]
> 安装（适用于React Native V0.5x.x或Expo SDK <v33）
> npm install --save react-native-signature-canvas@1.4.2

API 29, Android screen grey, nothing

**Comment by YanYuanFE** [comment]
请问下你的项目是react-native-cli创建的项目吗？能否提供一个能复现问题的最小代码例子，最好是Github仓库，以及复现问题的步骤，谢谢支持。

**Comment by mynameisliuyurong** [comment]
> 请问下你的项目是react-native-cli创建的项目吗？能否提供一个能复现问题的最小代码示例，最好是Github仓库，以及复现问题的步骤，谢谢支持。

All you need to do is open the build.Gradle file in your Android folder and change targetSdkVersion to 29.

**Comment by YanYuanFE** [comment]
Hi, @mynameisliuyurong ,you can try this example: https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/signapp, I run it with Android 10 and API 29, work fine.
