### ISSUE TITLE
Constant crash on Android 10

### ISSUE THREAD

**Issue by kevinstevanus** [YanYuanFE/react-native-signature-canvas#77]
whenever i open the signature canvas on android 6, its working perfectly. like console logging the base64 image and then goes back with stack navigation. 
but on android 10, it's constantly crashed the app(sudden crash happened without any traceable log).
i also tried this on physical device. both android 10 are having constant crash while android 6 didn't

how to reproduce the bug:
1. open the signature canvas on simulator(android 10)
2. go back from stack navigation
3. crash happened

im on sdk 39

this is on android 10:
![XIU034rwyp](https://user-images.githubusercontent.com/37767069/96484751-9c1c5a00-1266-11eb-9277-f90f24f79dd6.gif)

this is on android 6:
![C84b3qvZMa](https://user-images.githubusercontent.com/37767069/96486483-09c88600-1267-11eb-93a4-566d5c712ce6.gif)

**Comment by mynameisliuyurong** [comment]
Hello, can you share the code? Android doesn't show anything when my targetSdkVersion=10

**Comment by kevinstevanus** [comment]
`
import { useRef } from "react";
import React from "react";
import { StackActions } from "@react-navigation/native";
import SignatureScreen from "react-native-signature-canvas";

const Sign = ({ text, onOK, navigation }) => {
  const popAction = StackActions.pop(1);
  const ref = useRef();

  const handleSignature = (signature) => {
    console.log(signature);
    // navigation.dispatch(popAction);
    // onOK(signature);
  };

  const handleEmpty = () => {
    console.log("Empty");
  };

  const handleClear = () => {
    console.log("clear success!");
  };

  const handleEnd = () => {
    ref.current.readSignature();
  };

  return (
    <SignatureScreen
      ref={ref}
      onEnd={handleEnd}
      onOK={handleSignature}
      onEmpty={handleEmpty}
      onClear={handleClear}
      autoClear={true}
      descriptionText={text}
    />
  );
};

export default Sign;

`

**Comment by kevinstevanus** [comment]
weird, i just tested it again but with fresh start with `expo init` 
crash didn't happen. 
i think the crash might happen if there's a nested navigation on the project
will give more folllow up later.

**Comment by mynameisliuyurong** [comment]
> 怪异的是，我再次对其进行了测试，但是`expo init`
> 即使它在android 10上，也没有发生崩溃的全新开始。
> 我认为，如果项目上有嵌套导航，崩溃可能会在
> 以后发生。

My project ran flawlessly with targetSdkVersion=28

**Comment by YanYuanFE** [comment]
> Hello, can you share the code? Android doesn't show anything when my targetSdkVersion=10

react-native-webview在不同的sdk version有兼容性问题，有可能是这个原因

**Comment by YanYuanFE** [comment]
> weird, i just tested it again but with fresh start with `expo init`
> crash didn't happen even though it's on android 10.
> i think the crash might happen if there's a nested navigation on the project
> will give more folllow up later.

https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expoApp
this example use sdk39 and stack navigation, It's work fine on android 10.

**Comment by kevinstevanus** [comment]
it seems i've found where the problem is. on my conclusion it's not about navigation problems but from imports 
`import { enableScreens } from "react-native-screens";`
I will make new issue since it's a different topics

**Comment by gioramies** [comment]
I have the same issue:
1. Open the Screen where I'm using the SignatureScreen component.
2. Press device or app back button and crash.

I have found that if I scroll the screen until the SignatureScreen component appears in the screen, and press back button, it doesn't crash and works without problems.

Did you fix it? Thank you.

**Comment by kevinstevanus** [comment]
> I have the same issue:
> 
> 1. Open the Screen where I'm using the SignatureScreen component.
> 2. Press device or app back button and crash.
> 
> I have found that if I scroll the screen until the SignatureScreen component appears in the screen, and press back button, it doesn't crash and works without problems.
> 
> Did you fix it? Thank you.

i fixed the crash by deleting `import { enableScreens } from "react-native-screens";` from the js file.

**Comment by gioramies** [comment]
Thank you. I found a solution using the prop androidHardwareAccelerationDisabled={true}
