### ISSUE TITLE
Module is not a registered callable module (calling onMessage) on Android with Expo 39

### ISSUE THREAD

**Issue by ivangafa** [YanYuanFE/react-native-signature-canvas#78]
I updated my expo project to latest sdk version 39, and component breaks when calling onOk function.

**Comment by YanYuanFE** [comment]
Please make sure your Expo app version is up to date, and you can try this example: https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expoApp, I run it with android 10, work fine.

**Comment by ivangafa** [comment]
> Please make sure your Expo app version is up to date, and you can try this example: https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expoApp, I run it with android 10, work fine.

Thank you!. I notice that the version of react-native-web was differente, so I update it. It works.
