### ISSUE TITLE
onClear Clear signature before user confirm

### ISSUE THREAD

**Issue by hqlovely** [YanYuanFE/react-native-signature-canvas#79]
I tried to add the Alert to let user decide whether or not they want to clear, but when press the clear button the signature already clear before user press the alert.

 const handleClear = () => {
    Alert.alert(
      "Are you sure ?",
      "The signature will be remove",
      [
        {
          text: "Cancel",
          onPress: () => {
//Not Clear
},
          style: "cancel"
        },
        { text: "OK", onPress: () => {
//Clear Signature
} }
      ],
      { cancelable: false }
    );
  };

<SignatureScreen
            ref={ref}
            onOK={handleOk}
            autoClear={true}
            onClear={handleClear}
            descriptionText="
            backgroundColor="rgb(255,255,255)"
            webStyle={style}
          />

**Comment by YanYuanFE** [comment]
Hi, @hqlovely , The onClear function is triggered after the signature is cleared. If you want to prompt the user before clearing the signature, you can hide the button below, customize the confirmation and clear buttons use **Button** of RN, and then call the method of obtaining and clearing the signature through **ref.**： https://github.com/YanYuanFE/react-native-signature-canvas#methods

**Comment by hqlovely** [comment]
> Hi, @hqlovely , The onClear function is triggered after the signature is cleared. If you want to prompt the user before clearing the signature, you can hide the button below, customize the confirmation and clear buttons use **Button** of RN, and then call the method of obtaining and clearing the signature through **ref.**： https://github.com/YanYuanFE/react-native-signature-canvas#methods

Thanks
