### ISSUE TITLE
Can't write on Signature pad

### ISSUE THREAD

**Issue by Aishwaryashetty** [YanYuanFE/react-native-signature-canvas#8]
UI looks same, but when we try to sign, nothing happens , seems like something is broken, downgrading to 1.3.0 works fine

**Comment by YanYuanFE** [comment]
You can try a mini example of this repo。https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expoApp

**Comment by YanYuanFE** [comment]
I have reproduced this problem and found the reason, I will fix it immediately, I am sorry to bring you trouble.

**Comment by YanYuanFE** [comment]
I have released v1.4.2 to fix this problem.you can update to try it.

**Comment by jqtruong** [comment]
works great now, except when in a `ScrollView`. Created an issue #11.

**Comment by crisarge** [comment]
Hi, I have version v1.4.2 but I can't do anything in the view, they don't respond, nor can the buttons help me with this problem please

**Comment by YanYuanFE** [comment]
> Hi, I have version v1.4.2 but I can't do anything in the view, they don't respond, nor can the buttons help me with this problem please

Please provide your version of react native or expo, and show your code example.
