### ISSUE TITLE
Constant Crash when using `import { enableScreens } from "react-native-screens"`

### ISSUE THREAD

**Issue by kevinstevanus** [YanYuanFE/react-native-signature-canvas#81]
Hi, thank you for the beautiful project and I really loved it. but I want to report there's a bug regarding `react-native-screens` when used with your project. 

referencing [react navigation documentation](https://reactnavigation.org/docs/react-native-screens/) it said that `enableScreens()` are used for memory optimizations
here is the code 
`
import { enableScreens } from 'react-native-screens';`
`enableScreens();`

but when not used with your project, the signature screen runs smoothly like this 
![QFN3RuPhxD](https://user-images.githubusercontent.com/37767069/97522879-69dfca80-19d3-11eb-9450-c82844364759.gif)

and.. when it's used, it will became like this:
![CwlWfUB60P](https://user-images.githubusercontent.com/37767069/97522928-8a0f8980-19d3-11eb-8bd0-60704d1c5ff0.gif)

I've added sample project below, using signature screens provided from your project example
[checkCrashSignature.zip](https://github.com/YanYuanFE/react-native-signature-canvas/files/5456015/checkCrashSignature.zip)

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/97543937-e2f71600-1a03-11eb-8477-d86b6fe53ba6.png)
I run this example on this device, and It's work fine, no crash, You can remove the SignatureScreen page and try again, confirm whether is the problem of react-native-signature-canvas.

**Comment by YanYuanFE** [comment]
I find some same issue about **react-native-screens**, see there: https://github.com/software-mansion/react-native-screens/issues

**Comment by mgithubmessier** [comment]
@YanYuanFE  adding `androidHardwareAccelerationDisabled={true}` as a prop to WebView in your library amends this issue while we're waiting for **react-native-screens** and **react-native-webview** to come out with a more permanent fix. I was going to open a PR but I realized I need your permission.

**Comment by YanYuanFE** [comment]
@mgithubmessier v3.3.0 has release.
