### ISSUE TITLE
Issue when other components are available on the screen/page

### ISSUE THREAD

**Issue by smurfolan** [YanYuanFE/react-native-signature-canvas#9]
If I render the component together with some other custom components, they stay invisible until I do something on the signature pad. Once I type something on the pad, for example, the rest of the components become visible.

Expo version: 2.6.14
react-native: 0.57.1

**Comment by jqtruong** [comment]
add `overflow: 'hidden` to the parent component's style. It seems to be a `WebView` related problem.

**Comment by YanYuanFE** [comment]
Can you provide a example for this issue?

**Comment by smurfolan** [comment]
> Can you provide a example for this issue?

```
export default class SampleComponent extends React.Component {
    constructor(props) {
        super(props);     
    }
    render() {
        return (
            <ImageBackground 
                source={...} 
                style={styles.container}>
                <TextInput
                    style={{height: 40, borderColor: 'gray', borderWidth: 1}}
                    onChangeText={(text) => this.setState({text})}
                    value={this.state.text}
                />
                <Signature
                    onOK={(img) => console.log(img)}
                    descriptionText="Sign"
                    clearText="Clear"
                    confirmText="Save"
                />
            </ImageBackground>
        );
    }
}

const styles = StyleSheet.create({
    container:{
        flex: 1,
        width: '100%', 
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden'
    }
});
```

**Comment by YanYuanFE** [comment]
ImageBackground ? Can you provide the code of this component?

**Comment by smurfolan** [comment]
> ImageBackground ? Can you provide the code of this component?

It is part of `react-native`

**import { ImageBackground, StyleSheet, TextInput } from 'react-native';**

**Comment by YanYuanFE** [comment]
`
import React from 'react';
import Signature from 'react-native-signature-canvas';
import { ImageBackground, StyleSheet, TextInput, SafeAreaView, View } from 'react-native';

export default class App extends React.Component {
  constructor(props) {
      super(props);
      this.state = { signature: null }; 
  }
  handleSignature = signature => {
    console.log(signature);
    this.setState({ signature });
  };
  render() {
      return (
          <SafeAreaView style={styles.view}>
            <ImageBackground
                resizeMode="cover"
                source={{uri: "https://www.apicloud.com/news_image/1481181873543_image002.jpg"}} 
                style={styles.container}>
                <TextInput
                    style={{
                      height: 40, 
                      borderColor: 'gray', 
                      borderWidth: 1, 
                      width: "100%",
                      backgroundColor: "#FFF"
                    }}
                    onChangeText={(text) => console.log('Text')}
                    value={'None'}
                />
                <View style={{width: "100%", height: 300}}>
                  <Signature
                      onOK={(img) => console.log(img)}
                      descriptionText="Sign"
                      clearText="Clear"
                      confirmText="Save"
                  />
                </View>
            </ImageBackground>
          </SafeAreaView>
      );
  }
}

const styles = StyleSheet.create({
  container:{
      flex: 1,
      width: '100%', 
      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden'
  },
  view: {
    flex: 1,
    backgroundColor: "red"
  }
});
`

**Comment by YanYuanFE** [comment]
![image](https://user-images.githubusercontent.com/17774285/59245081-bb09e580-8c49-11e9-9396-9f12179f6af8.png)

**Comment by YanYuanFE** [comment]
I tried your example and it works.

**Comment by smurfolan** [comment]
> I tried your example and it works.

On a real device, using the following: 
Expo version: 2.6.14
react-native: 0.57.1

?

**Comment by YanYuanFE** [comment]
https://github.com/YanYuanFE/react-native-signature-canvas/tree/master/example/expoApp,
I use this code example to modify.
