### ISSUE TITLE
Modal Disappear Issue

### ISSUE THREAD

**Issue by udayan188** [YanYuanFE/react-native-signature-canvas#91]
Modal Disappered everytime when it finished signing
env 
"react": "16.13.1",
"expo": "^40.0.0",
"react-native-signature-canvas": "^3.3.0",
"react-native-webview": "^11.0.3"

```
`  constructor(props){
    super(props)
    this.myRef = React.createRef();
    this.state ={
      modalVisible: false,
    }
    
  }

  handleSignature = signature => {
    console.log(signature);
    this.setState({modalVisible: !this.state.modalVisible});
  };

  handleEmpty = () => {
    console.log('Empty');
  }

  handleClear = () => {
    console.log('clear success!');
  }

  handleEnd = () => {
    this.myRef.current.readSignature();
}

handleBegin = () => {
  console.log('begin!');
};

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.header}></View>
      <TouchableOpacity onPress={()=> this.setState({modalVisible : !this.state.modalVisible})}>
        <View
          style={{
            borderWidth:0.5,
            borderRadius:35,
            height: Dimensions.get("window").height * 0.5,
            width: "80%",
            alignSelf: "center",
          }}
        >
          
          <Modal
          visible={this.state.modalVisible}>
            <View style={{flex:1}}>
            <SignatureScreen
          ref={this.myRef}
          onEnd={this.handleEnd}
          onOK={this.handleSignature} 
          onEmpty={this.handleEmpty}
          onClear={this.handleClear}
          onBegin={this.handleBegin}
          autoClear={false} 
          confirmText="Save"
          backgroundColor="rgb(255,255,255)"
          penColor={"rgba(255,117,2,1)"}
          imageType="image/jpeg"
          minWidth={5}
      />
            </View>
          </Modal>
     
        </View>
        </TouchableOpacity>


      </View>
    );
  }
}`
```

**Comment by YanYuanFE** [comment]
```
handleSignature = signature => {
    console.log(signature);
    this.setState({modalVisible: !this.state.modalVisible});
  };
```
onOK been call when finished signing, so your modal hide.

**Comment by udayan188** [comment]
I just fix it with using custom onOK button

`  constructor(props) {
    super(props);
    this.myRef = React.createRef();
    this.state = {
      modalVisible: false,
    };
  }

  handleSignature = (signature) => {
    this.setState({ modalVisible: !this.state.modalVisible });

    console.log(signature);
  };

  handleEmpty = () => {
    console.log("Empty");
    Alert.alert("Please sign the doc");
  };

  handleClear = () => {
    this.myRef.current.clearSignature();
    console.log("clear success!");
  };

  render() {
    return (
      <View style={styles.container}>
        <View style={styles.header}></View>
        <TouchableOpacity
          onPress={() =>
            this.setState({ modalVisible: !this.state.modalVisible })
          }
        >
          <View
            style={{
              borderWidth: 0.5,
              borderRadius: 35,
              height: Dimensions.get("window").height * 0.5,
              width: "80%",
              alignSelf: "center",
            }}
          >
            <Modal visible={this.state.modalVisible}>
              <View style={{ flex: 1 }}>
                <SignatureScreen
                  ref={this.myRef}
                  webStyle={signwindow}
                  onOK={this.handleSignature}
                  onEmpty={this.handleEmpty}
                  autoClear={false}
                  backgroundColor="rgb(255,255,255)"
                  imageType="image/jpeg"
                  dataURL=""
                  minWidth={2}
                />
                <View
                  style={{
                    flexDirection: "row",
                    justifyContent: "space-around",
                  }}
                >
                  <TouchableOpacity
                    onPress={() => {
                      this.handleClear();
                    }}
                  >
                    <Text>X CLEAR</Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                    onPress={() => {
                      this.myRef.current.readSignature();
                    }}
                  >
                    <Text>SAVE</Text>
                  </TouchableOpacity>
                </View>
              </View>
            </Modal>
          </View>
        </TouchableOpacity>
       </View>`

**Comment by YanYuanFE** [comment]
说中文吧，你的问题是什么？期望什么结果，代码我看没问题的，弹窗关闭是你代码里面写的，onOK的回调里面关闭了弹窗

**Comment by udayan188** [comment]
Sorry I don't speak Chinese but this problem is on my part I didnt' expect onOK will automatically trigger after lifting a pen
sorry I'm just new to programming


this is before custom save button
![old](https://user-images.githubusercontent.com/58310256/104703441-e91aaa00-5749-11eb-8395-a05f1f529213.gif)

after custom save button
![new](https://user-images.githubusercontent.com/58310256/104703557-0e0f1d00-574a-11eb-8b88-1a3859408999.gif)

**Comment by YanYuanFE** [comment]
> onEnd={this.handleEnd}
Sorry, I thought you were Chinese, you don't need use onEnd, this.myRef.current.readSignature() in handleEnd function, onEnd function will call when you signing finished, then readSignature been call, then onOK been call, modal hide,
so you should remove onEnd prop.

**Comment by udayan188** [comment]
Thanks for clarifying case closed!

**Comment by kbqdev** [comment]
Still got this in react native 0.75.3
