### ISSUE TITLE
Gives me an error related to webview

### ISSUE THREAD

**Issue by TamasFarago** [YanYuanFE/react-native-signature-canvas#96]
I get this error : 
<img width="321" alt="Screenshot 2021-02-01 at 12 44 38" src="https://user-images.githubusercontent.com/67281301/106454644-5db05100-648b-11eb-88c2-5ec58e8866cc.png">

My Versions are: 
"react-native-signature-canvas": "^2.6.0",
"react-native-webview": "^11.0.2",

Is there any way to fix this problem?

**Comment by YanYuanFE** [comment]
Please install the latest version，v3.4.0

**Comment by TamasFarago** [comment]
Unfortunately I still get the same error after installing v3.4.0

**Comment by urvish91** [comment]
Still facing same issue.
